// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdqoeqsglhkdqnpkwzwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcW9lcXNnbGhrZHFucGt3endyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTU0OTAsImV4cCI6MjA4ODM5MTQ5MH0.YH7bNUgil7PBSRXlnxhx8pfKa4WdjEVjBludL67QBeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});